package com.db2020prj.reources;

import java.util.Random;

public class Icon {


    public static String random_icon() {
        return icons[random.nextInt(icons.length)];
    }

    private static Random random = new Random();

    private final static String[] icons = new String[] {
            "mdi-alpha",
            "mdi-alpha-a",
            "mdi-alpha-a-box",
            "mdi-alpha-a-box-outline",
            "mdi-alpha-a-circle",
            "mdi-alpha-a-circle-outline",
            "mdi-alpha-b",
            "mdi-alpha-b-box",
            "mdi-alpha-b-box-outline",
            "mdi-alpha-b-circle",
            "mdi-alpha-b-circle-outline",
            "mdi-alpha-c",
            "mdi-alpha-c-box",
            "mdi-alpha-c-box-outline",
            "mdi-alpha-c-circle",
            "mdi-alpha-c-circle-outline",
            "mdi-alpha-d",
            "mdi-alpha-d-box",
            "mdi-alpha-d-box-outline",
            "mdi-alpha-d-circle",
            "mdi-alpha-d-circle-outline",
            "mdi-alpha-e",
            "mdi-alpha-e-box",
            "mdi-alpha-e-box-outline",
            "mdi-alpha-e-circle",
            "mdi-alpha-e-circle-outline",
            "mdi-alpha-f",
            "mdi-alpha-f-box",
            "mdi-alpha-f-box-outline",
            "mdi-alpha-f-circle",
            "mdi-alpha-f-circle-outline",
            "mdi-alpha-g",
            "mdi-alpha-g-box",
            "mdi-alpha-g-box-outline",
            "mdi-alpha-g-circle",
            "mdi-alpha-g-circle-outline",
            "mdi-alpha-h",
            "mdi-alpha-h-box",
            "mdi-alpha-h-box-outline",
            "mdi-alpha-h-circle",
            "mdi-alpha-h-circle-outline",
            "mdi-alpha-i",
            "mdi-alpha-i-box",
            "mdi-alpha-i-box-outline",
            "mdi-alpha-i-circle",
            "mdi-alpha-i-circle-outline",
            "mdi-alpha-j",
            "mdi-alpha-j-box",
            "mdi-alpha-j-box-outline",
            "mdi-alpha-j-circle",
            "mdi-alpha-j-circle-outline",
            "mdi-alpha-k",
            "mdi-alpha-k-box",
            "mdi-alpha-k-box-outline",
            "mdi-alpha-k-circle",
            "mdi-alpha-k-circle-outline",
            "mdi-alpha-l",
            "mdi-alpha-l-box",
            "mdi-alpha-l-box-outline",
            "mdi-alpha-l-circle",
            "mdi-alpha-l-circle-outline",
            "mdi-alpha-m",
            "mdi-alpha-m-box",
            "mdi-alpha-m-box-outline",
            "mdi-alpha-m-circle",
            "mdi-alpha-m-circle-outline",
            "mdi-alpha-n",
            "mdi-alpha-n-box",
            "mdi-alpha-n-box-outline",
            "mdi-alpha-n-circle",
            "mdi-alpha-n-circle-outline",
            "mdi-alpha-o",
            "mdi-alpha-o-box",
            "mdi-alpha-o-box-outline",
            "mdi-alpha-o-circle",
            "mdi-alpha-o-circle-outline",
            "mdi-alpha-p",
            "mdi-alpha-p-box",
            "mdi-alpha-p-box-outline",
            "mdi-alpha-p-circle",
            "mdi-alpha-p-circle-outline",
            "mdi-alpha-q",
            "mdi-alpha-q-box",
            "mdi-alpha-q-box-outline",
            "mdi-alpha-q-circle",
            "mdi-alpha-q-circle-outline",
            "mdi-alpha-r",
            "mdi-alpha-r-box",
            "mdi-alpha-r-box-outline",
            "mdi-alpha-r-circle",
            "mdi-alpha-r-circle-outline",
            "mdi-alpha-s",
            "mdi-alpha-s-box",
            "mdi-alpha-s-box-outline",
            "mdi-alpha-s-circle",
            "mdi-alpha-s-circle-outline",
            "mdi-alpha-t",
            "mdi-alpha-t-box",
            "mdi-alpha-t-box-outline",
            "mdi-alpha-t-circle",
            "mdi-alpha-t-circle-outline",
            "mdi-alpha-u",
            "mdi-alpha-u-box",
            "mdi-alpha-u-box-outline",
            "mdi-alpha-u-circle",
            "mdi-alpha-u-circle-outline",
            "mdi-alpha-v",
            "mdi-alpha-v-box",
            "mdi-alpha-v-box-outline",
            "mdi-alpha-v-circle",
            "mdi-alpha-v-circle-outline",
            "mdi-alpha-w",
            "mdi-alpha-w-box",
            "mdi-alpha-w-box-outline",
            "mdi-alpha-w-circle",
            "mdi-alpha-w-circle-outline",
            "mdi-alpha-x",
            "mdi-alpha-x-box",
            "mdi-alpha-x-box-outline",
            "mdi-alpha-x-circle",
            "mdi-alpha-x-circle-outline",
            "mdi-alpha-y",
            "mdi-alpha-y-box",
            "mdi-alpha-y-box-outline",
            "mdi-alpha-y-circle",
            "mdi-alpha-y-circle-outline",
            "mdi-alpha-z",
            "mdi-alpha-z-box",
            "mdi-alpha-z-box-outline",
            "mdi-alpha-z-circle",
            "mdi-alpha-z-circle-outline",
    };
}

